### ISSUE TITLE
d3 is not defined

### ISSUE THREAD

**Issue by awhitford** [emdagon/meteor-c3js#1]
Trying a very basic c3 example:

``` javascript
Template.MyPage.rendered = function () {
  var chart = c3.generate({
    bindto: this.find('#myGraph'),
    data: {
      columns: [
        ['data1', 30, 200, 100, 400, 150, 250],
        ['data2', 50, 20, 10, 40, 15, 25]
      ]
    }
  });
};
```

Alas, I am getting an exception like:

```
Exception from Tracker afterFlush function: Cannot read property 'scale' of undefined
TypeError: Cannot read property 'scale' of undefined
    at ChartInternal.c3_chart_internal_fn.generateColor (http://localhost:3000/packages/emdagon_c3js.js?94cafaaee63d158139e3382ec66301b206705d92:5477:101)
    at ChartInternal.c3_chart_internal_fn.initParams (http://localhost:3000/packages/emdagon_c3js.js?94cafaaee63d158139e3382ec66301b206705d92:125:23)
    at ChartInternal.c3_chart_internal_fn.init (http://localhost:3000/packages/emdagon_c3js.js?94cafaaee63d158139e3382ec66301b206705d92:84:12)
    at new Chart (http://localhost:3000/packages/emdagon_c3js.js?94cafaaee63d158139e3382ec66301b206705d92:44:12)
    at Object.c3.generate (http://localhost:3000/packages/emdagon_c3js.js?94cafaaee63d158139e3382ec66301b206705d92:68:16)
```

I trapped the issue in the debugger and I can see that **d3 is undefined**, so the following code is running into issues:

``` javascript
    c3_chart_internal_fn.generateColor = function () {                                                                 // 5443
        var $$ = this, config = $$.config, d3 = $$.d3,                                                                 // 5444
            colors = config.data_colors,                                                                               // 5445
            pattern = notEmpty(config.color_pattern) ? config.color_pattern : d3.scale.category10().range(),           // 5446
            callback = config.data_color,                                                                              // 5447
            ids = [];                                                                                                  // 5448
```

Note that c3 is defined:

```
Object {version: "0.4.9", generate: function, chart: Object}
```

I also confirmed that d3js is included before c3:

``` html
  <script type="text/javascript" src="/packages/d3js_d3.js?143669b7a95b3f649beda008ede04424ece7be4e"></script>
  <script type="text/javascript" src="/packages/emdagon_c3js.js?94cafaaee63d158139e3382ec66301b206705d92"></script>
```

So, _why is d3 not defined?_

**Comment by awhitford** [comment]
Note that I proved that d3 is initializing.  The d3 instance can be accessed through _Package['d3js:d3']_: 

```
Package['d3js:d3'].d3
Object {version: "3.4.13", ascending: function, descending: function, min: function, max: function…}
```

But this doesn't explain how c3 can get access to it.  Note that _this_ at the _c3_chart_internal_fn.generateColor_ context is:

```
ChartInternal {d3: undefined, api: Chart, config: Object, data: Object, cache: Object…}
```

**Comment by awhitford** [comment]
If the following code is hacked:

``` javascript
    function ChartInternal(api) {
        var $$ = this;
        $$.d3 = window.d3 ? window.d3 : typeof require !== 'undefined' ? require("d3") : undefined;
        $$.api = api;
        $$.config = $$.getDefaultConfig();
        $$.data = {};
        $$.cache = {};
        $$.axes = {};
    }
```

such that:

``` javascript
        $$.d3 = Package['d3js:d3'].d3;
```

Then the chart works as expected.

(Note that I am NOT advocating such a hack; I'm merely pointing out that the problem is an initialization problem.)

**Comment by landm** [comment]
To those wondering about a solution. I got frustrated with c3 packages not working and played around with it and their initialization. Removing all d3 packages in your project adding back the d3js:d3 package and placing the c3.js, c3.css files in your client directory works as expected. I was unable to get a packaged version working. 

This issue is likely due to an intentional change in the scope of added packages and their dependencies by the MDG. However, there is probably a way to wrap the c3 package that works as adding it "manually" works just fine.

**Comment by emdagon** [comment]
This is odd, I'm currently using this package everyday... did you add d3js:d3 to your project manually? I had some difficulties while importing d3 as dependency for this package, but it is working properly since I added by itself:

```
$ meteor list
...
d3js:d3                      3.4.13* D3 (official): HTML/SVG/CSS visualization components to manipulate documents based on data
emdagon:c3js                 0.0.1  C3.js Charts for Meteor
```

Also, I'm initializing the chart the same way as you are... @awhitford are you sure is #myGraph a div in your DOM?

**Comment by landm** [comment]
It looks like I had a dependency on d3 added by another package. This version of d3 was old (3.0.3) and was the version c3 was picking up to use, not the d3js:d3 package. Eliminating all other d3 dependencies and ensuring d3js:d3 is added to the project first by itself and then adding this c3 package works for me.
